name: Build and Push Java Maven Project
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: default-username
          password: default-password
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hsati/repository-platform
          registry: docker.io
          tags: latest
